#!/usr/bin/env bash

################################################################################
# Prepare environment
################################################################################

function usage() {
    local -r script="${1}"
    local -r argument="${2}"

    echo >&2 -e "Invalid argument: ${argument}"
    echo >&2 -e "Usage: ${script} [--sources_path=<sources_path>] [--debug]"
    exit "${LINENO}"
}

# exit immediately when a command fails
set -Eeo pipefail

# treat unset variables as an error
set -u

readonly scripts_path="$( cd "$(dirname "${0}")" ; pwd -P )"
readonly root_repository_path="$( cd "${scripts_path}"; git rev-parse --show-toplevel )"

################################################################################
# Parse arguments
################################################################################

sources_path="${root_repository_path}"

for argument in "$@"; do
    if [[ "${argument}" == "--debug" ]]; then set -x

    elif [[ "${argument}" == "--sources_path="* ]]; then sources_path="$( realpath "${argument#--sources_path=*}" )"

    else usage "${0}" "${argument}"; fi
done

################################################################################
# Execute
################################################################################

cd "${sources_path}"

find . -path "*.swift" -print0 ! -path "/.build" ! -path "/.git" ! -path "/.swiftpm" ! -path "/Pods" | xargs -0 wc -l
