#!/usr/bin/env bash

# Source: https://github.com/hectr/xcode-development-scripts

################################################################################
# Prepare environment
################################################################################

function usage() {
    local -r script="${1}"
    local -r argument="${2}"

    echo >&2 -e "Invalid argument: ${argument}"
    echo >&2 -e "Usage: ${script} [--debug]"
    exit "${LINENO}"
}

# exit immediately when a command fails
set -Eeo pipefail

# treat unset variables as an error
set -u

readonly scripts_path="$( cd "$(dirname "${0}")" ; pwd -P )"
readonly root_repository_path="$( cd "${scripts_path}"; git rev-parse --show-toplevel )"

################################################################################
# Parse arguments
################################################################################

search_path="${root_repository_path}"

for argument in "$@"; do
    if [[ "${argument}" == "--debug" ]]; then set -x

    elif [[ "${argument}" == "--search_path="* ]]; then search_path="$( realpath "${argument#--search_path=*}" )"

    else usage "${0}" "${argument}"; fi
done

################################################################################
# Execute
################################################################################

cd "${search_path}"

IFS=";"
find "$( pwd )" -type d -name "*.xcworkspace" | grep -v "/.build/" | grep -v "/.swiftpm/" | grep -v ".xcodeproj/project.xcworkspace"
