#!/usr/bin/env bash

################################################################################
# Prepare environment
################################################################################

function usage() {
    local -r script="${1}"
    local -r argument="${2}"

    echo >&2 -e "Invalid argument: ${argument}"
    echo >&2 -e "Usage: ${script} [--version=<mint_version>] [--debug]"
    exit "${LINENO}"
}

# exit immediately when a command fails
set -Eeo pipefail

# treat unset variables as an error
set -u

################################################################################
# Parse arguments
################################################################################

mint_version=""

for argument in "$@"; do
    if [[ "${argument}" == "--debug" ]]; then set -x

    elif [[ "${argument}" == "--version="* ]]; then mint_version="@${argument#--version=*}"
    
    else usage "${0}" "${argument}"; fi
done

################################################################################
# Execute
################################################################################

readonly temp_dir_path="$( mktemp -d )"
cd "${temp_dir_path}"

git clone https://github.com/yonaskolb/Mint.git
cd Mint
swift run mint install "yonaskolb/mint${mint_version}"

rm -rf "${temp_dir_path}"
