#!/usr/bin/env bash

################################################################################
# Prepare environment
################################################################################

function usage() {
    local -r script="${1}"
    local -r argument="${2}"

    echo >&2 -e "Invalid argument: ${argument}"
    echo >&2 -e "Usage: ${script} [--gemfile_path=<gemfile_path>] [--debug]"
    exit "${LINENO}"
}

# exit immediately when a command fails
set -Eeo pipefail

# treat unset variables as an error
set -u

readonly scripts_path="$( cd "$(dirname "${0}")" ; pwd -P )"

################################################################################
# Parse arguments
################################################################################

gemfile_path="$( "${scripts_path}/root-directory-path" )"

for argument in "$@"; do
    if [[ "${argument}" == "--debug" ]]; then set -x

    elif [[ "${argument}" == "--gemfile_path="* ]]; then gemfile_path="$( realpath "${argument#--gemfile_path=*}" )"

    else usage "${0}" "${argument}"; fi
done

################################################################################
# Execute
################################################################################

cd "${gemfile_path}"

if [ -w "${HOME}/.gem" ]; then
    gem install bundler --no-document
else
    sudo gem install bundler --no-document
fi

bundle config set deployment 'true'
bundle install
